# Generated by Django 6.0.6 on 2026-06-08 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advogados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_processo', models.CharField(max_length=20, unique=True)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDO', 'Concluído')], default='ABERTO', max_length=20)),
                ('prioridade', models.CharField(choices=[('URGENTE', 'Urgente'), ('NAO_URGENTE', 'Não urgente')], default='NAO_URGENTE', max_length=20)),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('data_audiencia', models.DateTimeField(blank=True, null=True)),
                ('advogado_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='advogados.advogado')),
            ],
        ),
    ]
