# Generated by Django 6.0.6 on 2026-06-08 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advogados', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advogado',
            old_name='data_criacao',
            new_name='data_registro',
        ),
    ]
